name: Update Manifest on Develop Change

on:
  push:
    branches:
      - feature/search

jobs:
  detect-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Determine frontend image version
        id: frontend-version
        run: |
          CURRENT_VERSION=$(grep -oP 'kimms1/dapanda-frontend-nextjs:\K[0-9]+\.[0-9]+' manifest/front/frontend.yaml)
          if [ -z "$CURRENT_VERSION" ]; then
            CURRENT_VERSION=1.0
          fi
          MAJOR_VERSION=$(echo $CURRENT_VERSION | cut -d '.' -f 1)
          MINOR_VERSION=$(echo $CURRENT_VERSION | cut -d '.' -f 2)
          if echo "${{ github.event.head_commit.message }}" | grep -q 'Release frontend'; then
            MAJOR_VERSION=$(echo "$MAJOR_VERSION + 1" | bc)
            MINOR_VERSION=0
          else
            MINOR_VERSION=$(echo "$MINOR_VERSION + 1" | bc)
          fi
          NEW_VERSION="$MAJOR_VERSION.$MINOR_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
      - name: Build and Push frontend Image
        run: |
          docker build -t kimms1/dapanda-frontend-nextjs:${{ env.NEW_VERSION }} .
          docker push kimms1/dapanda-frontend-nextjs:${{ env.NEW_VERSION }}
      - name: Update frontend.yaml
        run: |
          sed -i 's|image: kimms1/dapanda-frontend-nextjs:[^ ]*|image: kimms1/dapanda-frontend-nextjs:${{ env.NEW_VERSION }}|' manifest/front/frontend.yaml
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add manifest/front/frontend.yaml
          git commit -m "Update Docker images in manifest files with ${{ env.NEW_VERSION }}"
          if echo "${{ github.event.head_commit.message }}" | grep -q 'Release frontend'; then
            git tag -a "v${{ env.NEW_VERSION }}" -m "Release version ${{ env.NEW_VERSION }}"
            git push origin "v${{ env.NEW_VERSION }}"
          fi
          git push origin main
